module.exports={
    data:{
        "followed_tests":[
            {
                "test_id":"2565",
                "test_desc":"Creatinine (B)",
                "min_lim":0.67,"max_lim":1.17,
                "result":0.93,"units":"mg/dl",
                "message":"","is_messages":"0",
                "is_vitek":false,
                "vitek_row":[],
                "numeric_percentage":0,
                "is_follow":true,
                "result_file":null,
                "message_list":[],
                "time_stamp":null,
                "hash":null,
                "lab_date":"2019-07-14T00:00:00"
            },
            {
                "test_id":"25651",
                "test_desc":"eGFR",
                "min_lim":0.0,
                "max_lim":0.0,
                "result":105.0,
                "units":"ml/min/1.73m²",
                "message":"",
                "is_messages":"1",
                "is_vitek":false,
                "vitek_row":[],
                "numeric_percentage":0,
                "is_follow":true,
                "result_file":null,
                "message_list":[".60 ערך רצוי מעל"],
                "time_stamp":null,
                "hash":null,
                "lab_date":"2019-07-14T00:00:00"
            },
            {
                "test_id":"4075",
                "test_desc":"ALKP-Alkaline Phosphatase",
                "min_lim":30.0,
                "max_lim":120.0,
                "result":78.0,
                "units":"u/l",
                "message":"",
                "is_messages":"0",
                "is_vitek":false,
                "vitek_row":[],
                "numeric_percentage":0,
                "is_follow":true,
                "result_file":null,
                "message_list":[],
                "time_stamp":null,
                "hash":null,
                "lab_date":"2018-05-30T00:00:00"
            },
            {
                "test_id":"50223",
                "test_desc":"Hemoglobin",
                "min_lim":13.5,
                "max_lim":18.0,
                "result":15.0,
                "units":"g/dl",
                "message":"",
                "is_messages":"0",
                "is_vitek":false,
                "vitek_row":[],
                "numeric_percentage":0,
                "is_follow":true,
                "result_file":null,
                "message_list":[],
                "time_stamp":null,
                "hash":null,
                "lab_date":"2018-05-30T00:00:00"
            }
        ]
    }
    
}